# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60010c7ce1aca029664e8305820bfbcc070115b73eee7d996f89affda547919524c503a69506afcffae1ea7d8d460bd85d6f7b90616093fb01ee1ed5ffde209

test:
  secret_key_base: 941586c426146479ee33afeb9ac93d60715e29a9e6f0424384a734721ee661cb385119a374f1a98571e5fb391efb553ecd91d8dd0868d11fe16b8893d7b1c970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
